version: '3.9'

services:
  database_ignite:
    image: postgres
    container_name: database-rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTEGRES_USER=docker
      - POSTEGRES_PASSWORD=rentx
      - POSTEGRES_DB=rentx-api
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx-api
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database-rentx
    depends_on:
      - database-rentx

volumes:
  pgdata:
    driver: local
